radio: make it simpler

diff --git a/radio b/radio
--- a/radio
+++ b/radio
@@ -1,15 +1,16 @@
 #!/bin/sh
-# Simple radio script
+# about: simple wrapper for playing online radio streams
+alias player="amp"
+alias menu="dmenu -i -l 10"
 
-# List of streams
+# list of urls with station name
 LIST=$HOME/etc/radio/list
+# station name (either provide a exact name from the $LIST or choose using menu
+NAME=${1:-"$(cut -d ' ' -f1 $LIST | menu)"}
 
-URL="$(cut -d ' ' -f1 $LIST | dmenu -l 10 | xargs -I {} awk -F' ' "/{}/ {print \$2}" $LIST)"
-
-if [ -z "$URL" ]; then
-	printf 'Error: %s\n' 'No url provided' && exit 1
-else
-	amp "$URL"
-fi
+[ -n "$NAME" ] && player "$(awk -v F1="$NAME" '$1 ~ F1 {print $2}' $LIST)" || {
+	printf 'Error: %s\n' 'No url provided'
+	exit 1
+}
 
 exit $?
